version: "3"

services:
  mysql:
    container_name: mysqld
    image: mysql:${MYSQL_VERSOIN}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    command:
      - --server_id=1
      - --binlog_format=MIXED
      - --slow_query_log=1
      - --slow_query_log_file=/var/log/mysql/mysql-slow.log
      - --long_query_time=3
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --innodb_buffer_pool_size=8G
      - --innodb_buffer_pool_instances=8
      - --innodb_buffer_pool_chunk_size=1G
    ports:
      - ${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}
    volumes:
      - /mnt/data/mysql:/var/lib/mysql
      - /mnt/logs/mysql:/var/log/mysql

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    restart: always

  redis:
    container_name: redisd
    image: redis:5.0.7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_CONTAINER_PORT}

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd --config=/etc/nsqlookupd/nsqlookupd.conf
    networks:
      - nsq-network
    hostname: nsqlookupd
    ports:
      - "4161:4161"
      - "4160:4160"
    volumes:
      - ./nsqlookupd.conf:/etc/nsqlookupd/nsqlookupd.conf
      - ./logs/lookupd_log:/logs/lookupd_log

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -data-path=/nsq-data -mem-queue-size=1000000 -max-msg-timeout=24h -config=/etc/nsqd/nsqd.conf
    depends_on:
      - nsqlookupd
    networks:
      - nsq-network
    ports:
      - "4151:4151"
      - "4150:4150"
    volumes:
      - ./nsqd.conf:/etc/nsqd/nsqd.conf
      - ./data:/nsq-data
      - ./logs/nsqd_log:/logs/nsqd

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    hostname: nsqadmin
    ports:
      - "4171:4171"
    networks:
      - nsq-network

networks:
  nsq-network:
    driver: bridge
